### ISSUE TITLE
not compatible with KeenClient-PHP release 2.5.7 (guzzlehttp upgrade)

### ISSUE THREAD

**Issue by larsbo** [garethtdavies/keen-io-laravel#1]
The new KeenClient-PPHP release replaced `guzzle 3` with `guzzlehttp 6`: https://github.com/keenlabs/KeenClient-PHP/commit/256ac795b91fe70ba090d08959a508f42842679b

This produces the following error:

FatalThrowableError in GuzzleClient.php line 43: Type error: Argument 1 passed to GuzzleHttp\Command\Guzzle\GuzzleClient::__construct() must be an instance of GuzzleHttp\ClientInterface, none given, called in [...]\vendor\wensleydale\keen-io-laravel\src\KeenLaravelServiceProvider.php on line 40

**Comment by larsbo** [comment]
@garethtdavies  this could be solved by #2

**Comment by garethtdavies** [comment]
Cheers, merged.
