### ISSUE TITLE
Laravel 5.5 Autodiscovery

### ISSUE THREAD

**Issue by robbydooo** [garethtdavies/keen-io-laravel#3]
Hey,

Can we add autodiscovery for Laravel 5.5 apps to make it easier to install and maintain?

I can do a pull request if you want.

Thanks,
Rob

**Comment by robbydooo** [comment]
Any chance we can get @sekonda changes merged?

**Comment by garethtdavies** [comment]
Sorry, I utterly missed this and just found while cleaning my (neglected) repos. Checking this now and will merge.

**Comment by garethtdavies** [comment]
Closed with #4
